### ISSUE TITLE
"theme" variable conflicts with Github-pages new theme offering

### ISSUE THREAD

**Issue by budparr** [smartergiving/free-nonprofit-starter-website#2]
Just did a github-pages build with a fork of the theme and got this warning from Github:

> You are attempting to use a Jekyll theme, "default", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

I think that when they introduced Jekyll themes recently they reserved the word "theme" in the config file, so it's likely as simple as changing the name of the config variable. I'd be happy to submit a p.r. for this at some point, if that would be helpful. Really appreciate that you've created this.

**Comment by chadokruse** [comment]
Thanks for bringing this to my attention Bud! Went ahead and pushed the quick fix (you're right...was just a matter of changing the variable name).

**Comment by budparr** [comment]
Awesome. You've saved a friend of mine a lot of CMS woes today with this theme.
