### ISSUE TITLE
After cloning I'm getting 404 There isn't a GitHub Pages site here.

### ISSUE THREAD

**Issue by farmazon3000** [smartergiving/free-nonprofit-starter-website#3]
I've cloned your repor but it does not work, I'm getting:
```
404
There isn't a GitHub Pages site here.
```
when I try to reach my site url, i.e. https://sigmafund.github.io/

**Comment by JoelSalzesson** [comment]
Fixed as per http://stackoverflow.com/questions/40945331/getting-a-404-on-gh-pages-for-new-organisation. Can be closed.

**Comment by ashfaqadib** [comment]
You can follow how he does it here-
https://youtu.be/oa9cnWTpqP8?list=PLmTke4RiHujnyeMdM_06TBjB6Z5x-FTP_&t=3367
