### ISSUE TITLE
Update design

### ISSUE THREAD

**Issue by chadokruse** [smartergiving/free-nonprofit-starter-website#5]
Really like the simplicity of:
https://evie.undraw.co/

Fully open source 👍

PRs welcome!

**Comment by sPrhr** [comment]
greetings,
I would be more than happy to update the design for this template
if you can please assign me on this

**Comment by AfaGaming** [comment]
This was in 2019. I doubt this person is still monitoring this issue.

**Comment by chadokruse** [comment]
Thanks for the ping. I added this issue for a Hacktoberfest drive focused on nonprofits many years ago.

There are far better options for nonprofits nowadays (this was created seven years ago), so I'll remove the help-wanted tag and close this issue.

Of course, feel free to fork and update as you see fit. I'll likely archive the project once I get some time to see if it's still used/needed. 🙌
